files:
  - source: /src/MitternachtBot/data/*/**/*.json
    translation: /src/MitternachtBot/locale/%locale%/%original_file_name%
  - source: /src/MitternachtBot/locales/de-DE.yml
    translation: /src/MitternachtBot/locales/%locale%.yml
