version:                 '3.3'
services:
  postgres:
    image:               'postgres:12'
    volumes:
      -                  'db-data:/var/lib/postgresql/data'
    restart:             'always'
    environment:
      POSTGRES_DB:       'mitternacht'
      POSTGRES_USER:     'mitternacht'
      POSTGRES_PASSWORD: 'mitternacht'
  mitternacht:
    build:               '.'
    depends_on:
      -                  'postgres'
    volumes:
      -                  'mitternacht-data:/data'
    ports:
      -                  '${MITTERNACHT_WEB_PORT:?Port not provided.}:5000'
    restart:             'unless-stopped'
volumes:
  db-data:
  mitternacht-data:
