:toc:
:toc-placement!:

= Dokumentation Mitternachtbot

toc::[]

= Einrichtung des Bots

Für größtmögliche Portabilität und Einfachkeit wird empfohlen, die Installationsmethode <<Mit docker-compose,mit docker-compose>> zu verwenden.
Aktuell unterstützt diese Variante jedoch keine automatischen Updates.

Alternativ ist es möglich, eines der https://github.com/expeehaa/dotnet-build-run[dotnet-build-run-Skripte] zum Runterladen und Starten des Bots zu verwenden.
In dem Repository befinden sich zwei Skripte: Eins für die Ausführung mit Docker und eins ohne Docker.
Beide Skripte benötigen ähnliche Konfigurationsdateien und können selbstständig das Repository, in dem sich Mitternacht befindet, herunterladen.
Sie versuchen außerdem, den Bot automatisch zu updaten, falls dieser ohne Fehler gestoppt wird.

== Installation

=== Ohne Docker (dotnet-build-run)


=== Mit Docker (dotnet-build-run-docker)

Eine Beispielkonfiguration kann mit folgendem Befehl generiert werden.
[source,bash]
----
$ dotnet-build-run-docker --create-sample-config
----

Diese befindet sich dann in `build-run-docker-sample.cfg` und sieht ungefähr so aus:

[source,bash]
----
#!/bin/bash
# This is a sample configuration for the dotnet-build-run-docker script.

# The name of your application.
name="Sample"
repourl="sample.git"
branch="master"
# Root path of the script.
root="/home/user/git/dotnet-build-run"
# Name of the repository directory in $rootdir.
sourcedir="${root}/source"
# Name of the directory containing shared data (configurations, ...).
datadir="${root}/data"
# Name of the executable.
executable="Sample.dll"
# Additional arguments to "docker run".
docker_run_args=""
----

Standardmäßig zeigt `root` auf das Verzeichnis, in dem der Befehl ausgeführt wurde.

Für Mitternacht müssen einige Veränderungen vorgenommen werden.

[source,bash]
----
#!/bin/bash

name="uniquename"
repourl="https://github.com/Midnight-Myth/Mitternacht-NEW.git"
branch="master"
root="/path/to/the/bot/root/directory"
sourcedir="${root}/source"
datadir="${root}/data"
executable="Mitternacht.dll"
docker_run_args=""
----

Dabei ist zu beachten, dass das Feld `name` einen global eindeutigen, kleingeschriebenen Namen haben muss.
Dieser wird von docker als Imagename verwendet.
`root` kann auf ein beliebiges Verzeichnis verweisen, jedoch ist es sinnvoll, das Verzeichnis zu wählen, in dem sich die Konfigurationsdatei befindet.

Möchte man Mitternacht ohne Webinterface starten, muss `executable` auf `Mitternacht.dll` gesetzt werden.
Mit Webinterface sollte stattdessen `MitternachtWeb.dll` verwendet werden.
Außerdem, um das Webinterface außerhalb des Dockercontainers verfügbar zu machen, kann in `docker_run_args` ein Eintrag `-p=yourport:5000/tcp` hinzugefügt werden.
`yourport` muss dabei mit dem gewünschten Port ersetzt werden.
Es wird davon abgeraten, einen gängigen Port wie 80 oder 443 zu verwenden, stattdessen sollte ein Reverse-Proxy wie nginx genutzt werden, um das Webinterface öffentlich verfügbar zu machen.

Das Verzeichnis `datadir` wird für den Bot notwendige Konfigurationsdateien enthalten und mit einem laufenden Dockercontainer geteilt.

==== Starten des Bots

Zum Generieren der Botkonfigurationsdateien kann der Bot nun ausgeführt werden.
Der Befehl `dotnet-build-run-docker` liest standardmäßig eine Datei `build-run-docker.cfg` im aktuellen Verzeichnis.
Die modifizierte Beispielkonfiguration sollte entsprechend umbenannt werden.
Alternativ kann der Pfad zu einer beliebigen anderen Konfigurationsdatei als Argument angegeben werden.
Zum Starten kann der Befehl ausgeführt werden.

[source,bash]
----
$ dotnet-build-run-docker
----

Es wird zunächst das Repository in `sourcedir` geklont oder, falls schon vorhanden, auf den aktuellsten Commit in `branch` geupdatet.
Danach wird ein Dockerimage erstellt und der Bot gestartet.
Der Start sollte mit folgender Nachricht abbrechen:

[source]
----
12:20:09 Mitternacht.Services.Impl.BotCredentials | 'credentials.json' is missing. Add it and restart the program. An example can be found in /data/credentials_example.json
----

=== Mit docker-compose

Grundvoraussetzungen für diese Methode sind eine aktuelle Version von `docker-compose` und `docker>=19.03.0`.
Im Gegensatz zur Variante mit dem <<Mit Docker (dotnet-build-run-docker),dotnet-build-run-docker Skript>> wird hier kein zusätzlicher Prozess, wie bspw. eine `tmux`-Session, benötigt.
Das hat jedoch zum Nachteil, dass der Bot nicht mehr in der Lage ist, sich selbst zu updaten.

Die folgenden Erklärungen nutzen das Verzeichnis `mybot` als Hauptverzeichnis für das geklonte Botrepository.
Der Name kann selbstverständlich (und sollte) mit einem beliebigen anderen Namen ausgetauscht werden.
Dieser Name ist gleichzeitig auch Präfix für docker images, container und volumes.

==== Klonen des Repositories

Der Bot kann mit folgendem Befehl geklont werden.

[source,bash]
----
$ git clone --recurse-submodules https://github.com/Midnight-Myth/Mitternacht-NEW mybot
$ cd mybot
----

Standardmäßig wird der Branch `master` ausgecheckt, der gleichzeitig auch der stabile Branch ist.

==== Konfiguration für docker-compose

Als nächstes müssen Einstellungen für `docker-compose` festgelegt werden.
Dazu kann die Datei `example.env` zu `.env` kopiert werden.

[source,bash]
----
$ cp example.env .env
----

Die folgende Tabelle listet alle Konfigurationsmöglichkeiten

|====
| MITTERNACHT_WEB_PORT | Der Port, unter dem das Webinterface über die Hostmaschine erreichbar ist.
|====

Die aktuelle Dockerunterstützung ist darauf ausgerichtet, dass das Webinterface hinter einem Reverseproxy aktiv ist.
Möglicherweise wird die Option `MITTERNACHT_WEB_PORT` daher in Zukunft wegfallen.

==== Der erste Start des Bots

Der Bot muss konfiguriert werden, um richtig zu funktionieren.
Da am Anfang die nötigen Konfigurationsdateien fehlen, kann man sich Beispieldateien generieren lassen.

Dazu kann man den Bot mit

[source,bash]
----
$ docker-compose up
----

starten und mit `Ctrl+C` beenden, sobald die folgende Nachricht auftritt.

[source]
----
12:20:09 Mitternacht.Services.Impl.BotCredentials | 'credentials.json' is missing. Add it and restart the program. An example can be found in /data/credentials_example.json
----

Mit folgendem Befehl kann man in eine Sh-Umgebung gelangen, die Zugriff auf die Konfigurationsdateien gibt.
Als Editor vorinstalliert ist aus Gründen der Einfachkeit `nano`.

[source,bash]
----
$ docker-compose run mitternacht /bin/sh
----

Alternativ kann man auch direkt in das Datenverzeichnis schauen, das `docker` erstellt.
Dieses kann mit folgendem Befehl gefunden werden.

[source,bash]
----
$ docker volume inspect mybot_mitternacht-data -f '{{.Mountpoint}}'
----

Dieses Verzeichnis wird im Container des Bots unter `/data` gemountet.
Auf dem Hostsystem ist es zum Beispiel unter `/var/lib/docker/volumes/mybot_mitternacht-data/_data` zu finden.
In diesem Fall ist zu beachten, dass Zugriff darauf im Allgemeinen `root`-Berechtigungen benötigt.

Der Pfad zu der oben angegebenen Datei `/data/credentials_example.json` wäre dementsprechend auf dem Hostsystem `/var/lib/docker/volumes/test_mitternacht-data/_data/credentials_example.json`.

Weitere Informationen zur Konfiguration selbst gibt es in der Sektion <<Konfiguration>>.

==== Reguläres Starten und Stoppen des Bots

[source,bash]
----
# Start
$ docker-compose up -d

# Stop
$ docker-compose down
----

==== Updates

Mit den folgenden Befehlen, ausgeführt im Verzeichnis `mybot`, wird der Bot geupdatet.

[source,bash]
----
$ docker-compose down
$ git pull --ff-only --recurse-submodules
$ docker-compose up -d --build
----

==== Speicherort der Daten

In `docker-compose.yml` werden zwei Volumes definiert: Eins für die Postgres-Datenbank und eins für die Konfigurations- und weitere Dateien des Bots.
Standardmäßig sind diese unter `/var/lib/docker/volumes/` zu finden.
Eine Kopie dieser Volumes reicht aus, um den Bot zum Beispiel auf einem anderen Computer mit gleichen Daten zum Laufen zu bringen.


== Konfiguration

=== PostgreSQL

=== credentials.json

Benenne die Datei `credentials_example.json` um in `credentials.json`.
Der Inhalt sollte bisher ungefähr so aussehen:

[source,json]
----
{
  "ClientId": 0,
  "Token": "",
  "DbConnection": "Host=postgres;Port=5432;Database=mitternacht;Username=mitternacht;Password=mitternacht;",
  "OwnerIds": [
    0
  ],
  "GoogleApiKey": "",
  "MashapeKey": "",
  "LoLApiKey": "",
  "OsuApiKey": "",
  "CleverbotApiKey": "",
  "CarbonKey": "",
  "PatreonAccessToken": "",
  "PatreonCampaignId": "",
  "TotalShards": 1,
  "ShardRunCommand": "",
  "ShardRunArguments": "",
  "ShardRunPort": null,
  "ForumUsername": "",
  "ForumPassword": ""
}
----

Die folgende Tabelle bietet einen Überblick über die einzelnen Felder.

|====
| ClientId      | Die ClientId des Botaccounts.
| Token         | Das Token des Botaccounts.
| DbConnection  | Verbindung zur Datenbank, siehe <<PostgreSQL>> zur Einrichtung dieser. Wird der Bot mit <<docker-compose>> gestartet, muss am Standardwert nichts weiter verändert werden.
| OwnerIds      | Die IDs der Discordaccounts der Botbesitzer. Einige Befehle können nur von Botbesitzern ausgeführt werden.
| ForumUsername | Nutzername des Accounts, mit dem sich der Bot im GommeHD.net-Forum einloggt.
| ForumPassword | Passwort des Accounts, mit dem sich der Bot im GommeHD.net-Forum einloggt.
|====

=== mitternachtweb.config

Wird das Webinterface gestartet, reicht `credentials.json` nicht aus.
Im gleichen Verzeichnis wird noch eine Datei `mitternachtweb.config` benötigt mit folgendem Inhalt.

[source,json]
----
{
  "Discord": {
    "ClientId": 0,
    "ClientSecret": ""
  }
}
----

|====
| ClientId     | Die ClientId des Botaccounts
| ClientSecret | Das Client secret des Botaccounts
|====

= Botnutzung

== Globale Boteinrichtung

== Servereinrichtung

== Features

=== Geldsystem

=== Levelsystem

=== Userrolecolors
